CREATE TABLE TipoGasto (

Id INT NOT NULL PRIMARY KEY IDENTITY,
Nombre VARCHAR(40) NOT NULL,
Tipo VARCHAR(30) NOT NULL,

)

CREATE TABLE Gasto (

	Id INT NOT NULL PRIMARY KEY IDENTITY,
	IdTipoGasto INT NOT NULL,
	Valor DECIMAL NOT NULL,
	Fecha DATETIME NOT NULL,

	FOREIGN KEY (IdTipoGasto) REFERENCES TipoGasto(Id)
)


CREATE TABLE Usuario(

	Id INT NOT NULL PRIMARY KEY IDENTITY,
	Nombre VARCHAR(50) NOT NULL,
	R50 INT NOT NULL,
	R30 INT NOT NULL,
	R20 INT NOT NULL,

)